spring:
  application:
    name: TaskManager

server:
  port: 8080

logging:
  level:
    ru.t1.ismailov.taskmanager.aspect: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
