spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db_t1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # change for validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    ru.t1.ismailov.taskmanager.aspect: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
